### ISSUE TITLE
Allow AppEngine to Auto Inject Secrets

### ISSUE THREAD

**Issue by harir91** [googleapis/python-secret-manager#11]
One nice thing about AWS or Heroku is the ability to auto inject secrets. 

Now that Google has an explicit secret manager (in beta), we should be able to auto inject those secrets into AppEngine. This way, we don't have to store some key (since this always is a point of failure). Not sure if in the scope of this project, but that would be awesome.

**Comment by busunkim96** [comment]
Hi @harir91! Thanks for the taking the time to file a feature request. This repository is primarily for issues related to the Python library for secret manager. Please file bugs and feature requests for the underlying API in the [public issue tracker](https://issuetracker.google.com/issues/new?component=784854).

CC @sethvargo
