### ISSUE TITLE
Secret Manager not working when trying to access secrets locally

### ISSUE THREAD

**Issue by edgga** [googleapis/python-secret-manager#162]
#### Environment details

  - OS type and version: Windows 10
  - Python version: 3.9.6
  - pip version: 21.2.1
  - `google-cloud-secret-manager` version: 2.6.0

Okay, so basically I do not think that the issue is reproducible, I would guess that my GCP project got bugged somehow when someone in the company changed billing info for the project (that's about when the issues started).

Issue: I am able to access Google Secret Manager secrets when a Python script is ran on Compute Engine (default authentication) but when I try to run the script locally (authenticating via service account JSON file) I get an error saying:

`TypeError: Invalid constructor input for AccessSecretVersionRequest: 'projects/<project_name>/secrets/<secret_name>/versions/1'`

Both compute engine and the service account have Secret Manager Secret Accessor permissions so the permissions should not be at fault.

Another strange thing is that when the issue started happening inside the Secret Manager WEB UI instead of seeing my project name in the secret's path I started to see it's number:
![image](https://user-images.githubusercontent.com/65926599/127317978-cc71bfdc-7c84-48f9-a5cf-d1cfe779017f.png)

(I tried using project number as the project name when retrieving secret's without any luck also)

Compute Engine permissions for the Secret Manager:
![image](https://user-images.githubusercontent.com/65926599/127318991-07246857-fad9-42df-ab96-0ef0de68809a.png)
Service account permissions for the Secret Manager:
![image](https://user-images.githubusercontent.com/65926599/127318900-11b33cd2-8ff1-455a-b21b-fe0f593ce53b.png)

For some reason there is no project name near inheritance in the service account permissions.

#### Code example

I will copy paste the code that's used on the Compute Engine and on my local machine (it's pretty much the same):

**COMPUTE:**
```
    def get_api_keys(self):
        
        from google.cloud import secretmanager

        client = secretmanager.SecretManagerServiceClient()

        name = client.secret_version_path('<project_name>', '{}_{}_{}'.format(self.company, self.psp, self.product), 1)

        response = client.access_secret_version(name)

        secret = response.payload.data.decode('UTF-8')
        private_key, public_key = secret.split(',')

        private_key = private_key.replace('\n', '')
        public_key = public_key.replace('\n', '')
        
        return private_key, public_key
```

**LOCAL:**
```
    def get_api_keys(self):

        from google.cloud import secretmanager

        client = secretmanager.SecretManagerServiceClient.from_service_account_json(service_account_json)

        name = client.secret_version_path('<project_name>', '{}_{}_{}'.format(self.company, self.psp, self.product), 1)

        response = client.access_secret_version(name)

        secret = response.payload.data.decode('UTF-8')
        private_key, public_key = secret.split(',')

        private_key = private_key.replace('\n', '')
        public_key = public_key.replace('\n', '')
        
        return private_key, public_key
```

I have tried reporting a bug through GCP web but got no reply regarding the issue. Hope you can help!

**Comment by Sita04** [comment]
It looks to me that the API call  `client.access_secret_version` expects argument of the format `client.access_secret_version(request={"name": name})` instead of `client.access_secret_version(name)`.

Please refer to this [code sample](https://cloud.google.com/secret-manager/docs/samples/secretmanager-access-secret-version?hl=en#code-sample) to modify the script params.

Anyway, running the script via Compute Engine should have also thrown the same error. Could you re-confirm that your old code runs without any error via Compute Engine?

**Comment by parthea** [comment]
I'm going to close this issue due to inactivity but please feel free to re-open it with more information.
