### ISSUE TITLE
Bug in CodeOwners file

### ISSUE THREAD

**Issue by msampathkumar** [googleapis/python-secret-manager#371]
Please check https://screenshot.googleplex.com/8KPy4ZYbdw4Eyer.png

While browsing https://github.com/googleapis/python-secret-manager/blob/main/.github/CODEOWNERS  found error `This CODEOWNERS file contains errors`

```
Unknown owner on line 12: make sure the team @googleapis/python-samples-reviewers exists and has write access to the repository
/samples/   @googleapis/python-samples-reviewers
```

**Comment by parthea** [comment]
Fixed. Thanks @msampathkumar !
