### ISSUE TITLE
AttributeError: type object 'Credentials' has no attribute 'with_quota_project' (Error code: 0)

### ISSUE THREAD

**Issue by louixp** [googleapis/python-secret-manager#38]
#### Environment details

  - OS type and version: Google Cloud AI Platform custom prediction routine (runtime version 1.15)
  - Python version: 3.7
  - pip version: 20.1
  - `google-cloud-secret-manager` version: 1.0.0

#### Steps to reproduce
Importing secretmanager in [custom prediction interface](https://cloud.google.com/ai-platform/prediction/docs/custom-prediction-routines#predictor-class) causes attribute error.

#### Code example

```python
from google.cloud import secretmanager
```

#### Stack trace
```
AttributeError: type object 'Credentials' has no attribute 'with_quota_project' (Error code: 0)
```

**Comment by busunkim96** [comment]
@louixp Can you let me know what version of `google-auth` and `google-api-core` you are using?

**Comment by louixp** [comment]
google-api-core-1.22.0 
google-auth-1.20.1

**Comment by busunkim96** [comment]
Hmm, those versions of the libraries look fine to me.

@telpirion Is there something special about Auth with AI Platform?

**Comment by meredithslota** [comment]
I'm closing this out since it's stale, and we never got a solid repro here — but if this is still happening, please do open a new issue and detail the errors you're seeing. Thanks!
