### ISSUE TITLE
PermissionDenied: 403 Permission 'secretmanager.versions.access' denied for resource 'projects/project-b/secrets/stockdata-key/versions/1' (or it may not exist).

### ISSUE THREAD

**Issue by digitalghost-dev** [googleapis/python-secret-manager#389]
I'm trying to use Secret Manager instead of downloading JSON keys but it's been hard and confusing to set this up.
I currently have two projects: `project-a` and `project-b`.

In `project-a`, I use Cloud Run to host my website. I use Flask and have a route setup that connects to a BigQuery table that is in `project-b`.

First, I'm not sure in which project I should create the secret. In `project-a` where the Cloud Run service is or `project-b` where the BigQuery table is?
I've tried both.

Here is my Python code:
```
def access_secret_version():

    # Create the Secret Manager client, got this code from Google Docs
    client = secretmanager.SecretManagerServiceClient()

    # Build the resource name of the secret version.
    name = "projects/project-b/secrets/stockdata-key/versions/1"

    # Access the secret version.
    response = client.access_secret_version(request={"name": name})

    payload = response.payload.data.decode("UTF-8")
    return payload
---
@app.route('/projects/random-page')
def my_func():
    payload = access_secret_version()
    # Authenticating service account.

    os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = payload
```

When I deploy the code and try to visit the page, I get a `500 Internal Server Error` and Error Reporting states the error: `PermissionDenied: 403 Permission 'secretmanager.versions.access' denied for resource 'projects/project-b/secrets/stockdata-key/versions/1' (or it may not exist).`

I have given the roles of `Owner` and `Secret Manager Admin` to every service account I have and nothing seems to work.

**Comment by iennae** [comment]
@digitalghost-dev I'm not sure if you have everything you need, in case someone is looking for this at a later point and has the same questions going to drop some resources here 

https://cloud.google.com/run/docs/configuring/secrets#command-line
https://dev.to/googlecloud/serverless-mysteries-with-secret-manager-libraries-on-google-cloud-3a1p

**Comment by digitalghost-dev** [comment]
@iennae thank you, I just closed it because I wasn't sure if someone was going to help. I'll take a look at those links.
