### ISSUE TITLE
Documentation for python secret manager v2

### ISSUE THREAD

**Issue by aaryamannchallani** [googleapis/python-secret-manager#48]
A couple functions we were using from v1 were deprecated in v2.
Please let me know when the docs for v2 are out.

**Comment by busunkim96** [comment]
Hi @aaryamannchallani,

I just triggered the docs build so the new documentation should be available in the next hour.

**Comment by aaryamannchallani** [comment]
Awesome. Thanks @busunkim96

**Comment by aaryamannchallani** [comment]
You might want to update the quickstart available at this [link](https://cloud.google.com/secret-manager/docs/reference/libraries) too, doesn't work with v2

**Comment by busunkim96** [comment]
2.0 docs are now published: https://googleapis.dev/python/secretmanager/latest/index.html

I think the cloud.google.com docs are still pulling samples from the old repository. Updated samples can be found at https://github.com/googleapis/python-secret-manager/tree/master/samples/snippets.

**Comment by aaryamannchallani** [comment]
Cool, thanks a lot.
