### ISSUE TITLE
Docs don't link to definitions for object types

### ISSUE THREAD

**Issue by alexcwatt** [googleapis/python-secret-manager#51]
I hit a little snag understanding the docs for `get_secret`. I was unable to easily find the details on what the object looked like for the `request` parameter. I expected to find the docs for a `GetSecretRequest` but instead saw in the docs: `The request object. Request message for [SecretManagerService.GetSecret][google.cloud.secrets.v1beta1.SecretManagerService.GetSecret]`. I'm not sure why the linking didn't work but perhaps the docs for the SecretManagerService aren't being built, so the link couldn't be built, or perhaps the linking is not setup correctly.

Here is a link to the docs that I am seeing: https://googleapis.dev/python/secretmanager/latest/secretmanager_v1beta1/services.html#google.cloud.secretmanager_v1beta1.services.secret_manager_service.SecretManagerServiceClient.get_secret (latest = 2.0.0)

**Comment by busunkim96** [comment]
Hi @alexcwatt,

Thanks for the feedback on the documentation.  I think you're running into two problems at the moment. The first is that the docstrings have references that make sense in the API [protos](https://github.com/googleapis/googleapis/blob/215c12ade72d9d9616457d9b8b2f8a37f38e79f3/google/cloud/secretmanager/v1/service.proto#L277) but don't get translated by the client library generator. https://github.com/googleapis/gapic-generator-python/issues/483

The second issue is that the types are specified in the docstrings don't seem to be sufficient for link creation by sphinx. https://github.com/googleapis/gapic-generator-python/issues/480

For now, the client object and methods are in the ["Services for ..." page](https://googleapis.dev/python/secretmanager/latest/secretmanager_v1/services.html) and library (that includes request/response objects) are in the ["Types for ..." Page](https://googleapis.dev/python/secretmanager/latest/secretmanager_v1/types.html). You can also use quick search.

For `GetSecretRequest` specifically, see https://googleapis.dev/python/secretmanager/latest/secretmanager_v1/types.html#google.cloud.secretmanager_v1.types.GetSecretRequest

**Comment by alexcwatt** [comment]
Thanks @busunkim96 - I was able to find the info before opening the issue, so should have made that clear, but I wanted to highlight the docs issue. I've used some of the other Python packages for Google Cloud and hadn't run into this before. I appreciate you taking the time to point me to the info!

**Comment by meredithslota** [comment]
We've made lots of improvements to the docs since this issue was filed, including centralizing them in cloud.google.com here: https://cloud.google.com/python/docs/reference/secretmanager/latest/index.html and the `get_secret` method is described here: https://cloud.google.com/python/docs/reference/secretmanager/latest/google.cloud.secretmanager_v1.services.secret_manager_service.SecretManagerServiceClient#google_cloud_secretmanager_v1_services_secret_manager_service_SecretManagerServiceClient_get_secret I'm closing this out for now but please feel free to file a new issue if this doesn't solve your problem. Thanks!
