### ISSUE TITLE
The new version 2.3.0 broke access_secret_version()

### ISSUE THREAD

**Issue by penggaolai** [googleapis/python-secret-manager#90]
I had 2.2.0 installed and following code works fine

secret_response = secret_client.access_secret_version(request={"name": secret_name})

but after being upgraded to 2.3.0, I got following error: 

Argument "request" to "access_secret_version" of "SecretManagerServiceClient" has incompatible type "Dict[str, str]"; expected "Optional[AccessSecretVersionRequest]"

Please update your document accordingly.

**Comment by busunkim96** [comment]
Ah, I think that's because we started shipping the py.typed file.

A `dict` is accepted by the library, but our type annotations are incorrect. I opened https://github.com/googleapis/gapic-generator-python/issues/715 to track this.

Are you running a type checker @penggaolai?
